/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData cyclist = IconData(0xe8a3, fontFamily: _kFontFam);
  static const IconData swimmer = IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData pingPong = IconData(0xe8c3, fontFamily: _kFontFam);
  static const IconData soccerBall = IconData(0xe8e9, fontFamily: _kFontFam);
}
